<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PeladaPatronato.Application.Request\PeladaPatronato.Application.Request.csproj" />
    <ProjectReference Include="..\PeladaPatronato.Application.Response\PeladaPatronato.Application.Response.csproj" />
    <ProjectReference Include="..\PeladaPatronato.Domain\PeladaPatronato.Domain.csproj" />
  </ItemGroup>

</Project>
