// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeladaPatronato.Infra.Data.EntityFrameworkCore.Contexts;

#nullable disable

namespace PeladaPatronato.Infra.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(PeladaPatronatoDbContext))]
    [Migration("20260209020316_AddTabs_2300_08022026")]
    partial class AddTabs_2300_08022026
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdPosicaoPreferida")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("IdPosicaoPreferida");

                    b.ToTable("Participante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPosicao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Posicao", "PeladaPatronato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaPosicao = 1,
                            Nome = "Goleiro"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaPosicao = 2,
                            Nome = "Fixo"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaPosicao = 2,
                            Nome = "Ala"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaPosicao = 2,
                            Nome = "Pivo"
                        });
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<decimal>("ValorDiarista")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.ToTable("Rodada", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Minuto")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodadaParticipanteId");

                    b.ToTable("RodadaEvento", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CategoriaPosicao")
                        .HasColumnType("int");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RodadaTimeId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("RodadaParticipante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("GolsTimeA")
                        .HasColumnType("int");

                    b.Property<int>("GolsTimeB")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaTimeAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RodadaTimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RodadaTimeId");

                    b.ToTable("RodadaPartida");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId", "TimeId")
                        .IsUnique();

                    b.ToTable("RodadaTime", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Time", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Posicao", "Posicao")
                        .WithMany("Participantes")
                        .HasForeignKey("IdPosicaoPreferida");

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaEvento", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaParticipante", null)
                        .WithMany("Eventos")
                        .HasForeignKey("RodadaParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaParticipante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaTime", null)
                        .WithMany("Participantes")
                        .HasForeignKey("RodadaTimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartida", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaTime", null)
                        .WithMany("Partidas")
                        .HasForeignKey("RodadaTimeId");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Rodada", null)
                        .WithMany("Times")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Rodada", b =>
                {
                    b.Navigation("Times");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaParticipante", b =>
                {
                    b.Navigation("Eventos");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Partidas");
                });
#pragma warning restore 612, 618
        }
    }
}
