// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeladaPatronato.Infra.Data.EntityFrameworkCore.Contexts;

#nullable disable

namespace PeladaPatronato.Infra.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(PeladaPatronatoDbContext))]
    [Migration("20260206044859_AcertosBD")]
    partial class AcertosBD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdPosicaoPreferida")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("IdPosicaoPreferida");

                    b.ToTable("Participante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Posicao", "PeladaPatronato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nome = "Goleiro"
                        },
                        new
                        {
                            Id = 2,
                            Nome = "Fixo"
                        },
                        new
                        {
                            Id = 3,
                            Nome = "Ala"
                        },
                        new
                        {
                            Id = 4,
                            Nome = "Pivo"
                        });
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Posicao", "Posicao")
                        .WithMany("Participantes")
                        .HasForeignKey("IdPosicaoPreferida");

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
