// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PeladaPatronato.Infra.Data.EntityFrameworkCore.Contexts;

#nullable disable

namespace PeladaPatronato.Infra.Data.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(PeladaPatronatoDbContext))]
    [Migration("20260314032011_AddTable_RodadaTimeParticipantes_13032026_0019")]
    partial class AddTable_RodadaTimeParticipantes_13032026_0019
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.LegadoTotalEstatistica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar");

                    b.Property<int>("TotalAssistencias")
                        .HasColumnType("int");

                    b.Property<int>("TotalGols")
                        .HasColumnType("int");

                    b.Property<int>("TotalPartidas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.ToTable("LegadoTotalEstatistica", "Legado");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("varchar");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("varchar");

                    b.Property<int?>("IdPosicaoPreferida")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.Property<string>("NomeUsuario")
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.Property<int?>("Perfil")
                        .HasColumnType("int");

                    b.Property<bool>("PossuiAcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("SenhaHash")
                        .HasMaxLength(60)
                        .HasColumnType("varchar");

                    b.Property<string>("Telefone")
                        .HasMaxLength(11)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("IdPosicaoPreferida");

                    b.ToTable("Participante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaPosicao")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Posicao", "PeladaPatronato");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaPosicao = 1,
                            Nome = "Goleiro"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaPosicao = 2,
                            Nome = "Fixo"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaPosicao = 2,
                            Nome = "Ala"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaPosicao = 2,
                            Nome = "Pivo"
                        });
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Rodada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacao")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("TempoPorPartida")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("TempoTotal")
                        .HasColumnType("time");

                    b.Property<decimal>("ValorDiarista")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Rodada", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime");

                    b.Property<bool?>("Diarista")
                        .HasColumnType("bit");

                    b.Property<bool?>("Pago")
                        .HasColumnType("bit");

                    b.Property<Guid>("ParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParticipanteId");

                    b.HasIndex("RodadaId", "ParticipanteId")
                        .IsUnique();

                    b.ToTable("RodadaParticipante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataHora")
                        .HasColumnType("datetime");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeAId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeBId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TimeComPosseInicialId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.ToTable("RodadaPartida", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartidaEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaPartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaPartidaParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoEvento")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodadaPartidaId");

                    b.ToTable("RodadaPartidaEvento", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartidaParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaPartidaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RodadaPartidaId");

                    b.ToTable("RodadaPartidaParticipante");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("GolsContra")
                        .HasColumnType("int");

                    b.Property<int>("GolsPro")
                        .HasColumnType("int");

                    b.Property<Guid>("RodadaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TimeBaseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Vitorias")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RodadaId");

                    b.ToTable("RodadaTime", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTimeParticipante", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaParticipanteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RodadaTimeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RodadaTimeId");

                    b.ToTable("RodadaTimeParticipante", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Time", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Time", "PeladaPatronato");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.LegadoTotalEstatistica", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Participante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Posicao", "Posicao")
                        .WithMany("Participantes")
                        .HasForeignKey("IdPosicaoPreferida");

                    b.Navigation("Posicao");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaParticipante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Participante", "Participante")
                        .WithMany()
                        .HasForeignKey("ParticipanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PeladaPatronato.Domain.Entidades.Rodada", null)
                        .WithMany("Participantes")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartida", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Rodada", null)
                        .WithMany("Partidas")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartidaEvento", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaPartida", null)
                        .WithMany("Eventos")
                        .HasForeignKey("RodadaPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartidaParticipante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaPartida", null)
                        .WithMany("Participantes")
                        .HasForeignKey("RodadaPartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.Rodada", null)
                        .WithMany("Times")
                        .HasForeignKey("RodadaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTimeParticipante", b =>
                {
                    b.HasOne("PeladaPatronato.Domain.Entidades.RodadaTime", null)
                        .WithMany("Participantes")
                        .HasForeignKey("RodadaTimeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Posicao", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.Rodada", b =>
                {
                    b.Navigation("Participantes");

                    b.Navigation("Partidas");

                    b.Navigation("Times");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaPartida", b =>
                {
                    b.Navigation("Eventos");

                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("PeladaPatronato.Domain.Entidades.RodadaTime", b =>
                {
                    b.Navigation("Participantes");
                });
#pragma warning restore 612, 618
        }
    }
}
